#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "md5.h"

#if __has_include("fileutil.h")
#include "fileutil.h"
#endif

#define PASS_LEN 50     // Maximum length any password will be.
#define HASH_LEN 33     // Length of hash plus one for null.


int main(int argc, char *argv[])
{
    if (argc < 3) 
    {
        printf("Usage: %s hash_file dictionary_file\n", argv[0]);
        exit(1);
    }

    // hash array size variable
    int hashSize;

    // array of hashes being created by the loadFileAA function
    char **hashes = loadFileAA(argv[1], &hashSize);
    
    // operational array, where password is inputed there and trimmed out
    char optArr[1000];
    // counter for found password
    int i = 0;
    // pointer for the converted password into md5 hash value
    char *passHash;
    // signal variable generated by the linear search function
    int signal;
    

    // Open the password file for reading.
    FILE *passFile = fopen(argv[2], "r");

    if(!passFile){

        printf("ERROR 3: could not open the password file");
        exit(1);
    }

    // while passwords are available, start obtaining them with fgets
    while(fgets(optArr, PASS_LEN + 2, passFile)){


        // trimming the new line
        char *nl = strchr(optArr, '\n');
        if(nl){

            *nl = '\0';
        }

        // converting password to a hash value
        passHash = md5(optArr, strlen(optArr));

        // if signal is zero, strcmp was zero, which means values match
        signal = hashCmp(passHash, hashes, hashSize);
    
        // if signal was zero, print the password and the found hash value, and count
        if(signal == 0){

            printf("Found Password: %s --> Hash: %s\n", optArr, passHash);
            i++;

        }

        // free the mdf memory 
        free(passHash);
    }

    // close the file at the end and print the number of passwords found
    printf("number of passwords found --> %d", i);
    fclose(passFile);
    
}
